#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_GAME_TIMER_PERIOD 40.0E-3f


// Colors
#define CONFIG_COLOR_BACKGROUND rgb565(0, 4, 16)

#define CONFIG_COLOR_CURSOR WHITE
#define CONFIG_COLOR_STATUS WHITE

#endif // CONFIG_H_
